meta_name: "Focal Point"
meta_title: "Focal Point- Manage your team in one place!"
meta_description: "All in one app to manage and mesure your team."
meta_image: "Screenshot 2022-12-03 at 18.21.15.png" # should exist in `app/assets/images/`
